#!/bin/sh

###################################
#                                 #
# DO NOT TRY ON A WINDOWS MACHINE #
#                                 #
##################################

# This script edits commit message and attaches story number to commit message.

# NOTE: We assume story number is included in branch name
# For example, 'ABC-123-test-branch-name'

# After script executed, new commit message would be: "ABC-123 : your commit message"

# Copy and paste it into your `projectDirectory/.git/hooks`
# Make sure the file is executable by running `chmod +x commit-msg`

ticket=$(git symbolic-ref HEAD | perl -ne '/([A-Za-z]*-\d+)/; print "$1"')
merge=$(cat "$1" | perl -ne '/(Merge branch)/; print "$1"')

if [ -n "$merge" ]; then
    exit 0
elif [ -n "$ticket" ]; then
    echo "$ticket"' : '$(cat "$1") > "$1"
fi
