#!/bin/bash

# This script runs Android lint check before pushing your branch to remote.
# Copy and paste it into your `projectDirectory/.git/hooks`
# Make sure the file is executable by running `chmod +x pre-push

# Check if we actually have commits to push
commits=`git log @{u}..`

if [ -z “$commits” ]; then
 exit 0
fi

SIZE=1
while read -r line
do
    echo "$line"
    size=$(($SIZE + ${#line}))
done < <(./gradlew lintDebug testDebug)

if [ $SIZE -ne 0 ]; then
 echo -e "\n\n"
 echo “Failed Lint check. Please fix errors and warnings before pushing your branch.”
 echo -e "\n"
 exit 1
fi
exit 0
